### ISSUE TITLE
Scene imposter of Alicia cause artifacting

### ISSUE THREAD

**Issue by fire** [wojtekpil/Godot-Octahedral-Impostors#11]
![image](https://user-images.githubusercontent.com/32321/86056641-9dedb380-ba12-11ea-9b04-f11a81eb35f9.png)

https://github.com/vrm-c/UniVRM/tree/master/Tests/Models/Alicia_vrm-0.51

![GIF 2020-06-29 2-13-30 PM](https://user-images.githubusercontent.com/32321/86056761-ca093480-ba12-11ea-8ff0-813b467f6ef0.gif)

**Comment by fire** [comment]
To import you'll need to rename vrm to glb. You'll see some artifacting.

**Comment by wojtekpil** [comment]
Can you share your settings baking settings? Your impostor will look worse from the top, because its trying to blend between frames which are further apart then side views. There could be also  a problem with calculation of virtual plane I don't have a comparison to other bakers.  You could probably use something different than octahedral mapping but it's not application for this project. This method is optimized for VRAM usage. I couldn't reproduce your exact problem. Did you change something in shader? For example "Is Full Sphere" checkox ?

**Comment by fire** [comment]
I don't see anything that makes sense to be broken.

![image](https://user-images.githubusercontent.com/32321/86059992-b234af00-ba18-11ea-80ea-e1c88a8d2ff6.png)

**Comment by wojtekpil** [comment]
Maybe you changed some settings during baking. it would result in unexpected mapping problems. I didn't disable any UI controls, but it should be on my todo list. I tried to bake with this settings (T Pose is really bad for baking):
![Screenshot from 2020-06-30 00-22-46](https://user-images.githubusercontent.com/1286923/86061932-f4d1a800-ba67-11ea-9265-54b32c26e317.png)
It's overkill but results is pretty nice:
![model_high](https://user-images.githubusercontent.com/1286923/86062250-91944580-ba68-11ea-93fc-8e32d6eb1b67.gif)

**Comment by fire** [comment]
Are you using the latest 3.2.2 stable? I'm not able to recreate your results?

**Comment by wojtekpil** [comment]
Yes, it should work on 3.2.2.stable. I also tried it on 3.2.1.stable.  Please check this things:
1. Select baked images in Godot (base.png, norm_depth.png, orm.png) and check on the each of them in the import tab the number of horizontal and vertical slices. It should be equal to the "Grid size" parameter in baker.
2. Open generated image files by some external program and count images in row and column. It also should be equal to "Grid size"
2. On a scene tree select baked MeshInstance. Check its properties, go to Mesh -> Material -> Shader Param. 
  Check if "Imposter Frames" is, again, equal to "Grid size" parameter in baker. Also try checking/unchecking "Is Full Sphere"  
 Sometimes when I select wrong option here it looks like the problem you have (45 degree angle of models from some views).
3. Check if "Standard" Shader Type in baker gives you the same results. Working with TextureArrays in Godot is a little bit tricky right now.
4. You should also play with "Alpha Clamp"  and "Is Transparent" parameters in Shader. Those two should be optimized by hand, but I think that your problem is somewhere else.

**Comment by fire** [comment]
Will close issue because many things have changed in repository and I need to re-evaluate the problem.
